Выполнено домашнеее задание урока 1
roovenier/oshchepkov-alex-otus pull request #1
Opened 2023-12-02 10:20 UTC by roovenier

2023-12-09 19:22 UTC, nlapshin requested changes
Попробуйте поправить ошибку.

```
~/projects/dz/node-2023-11/oshchepkov-alex-otus/lesson-1 (nodejs-1 ✗) node ./index.js ./ -d 3
./ 3
├── README.md
├── assets
node:internal/validators:163
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
```

2023-12-09 19:22 UTC, nlapshin commented on lesson-1/index.js
> +const depthValue = process.argv[4];
Попробуйте обрабатывать аргументы в более надежной манере. Сейчас можно передать аргументы в чуть другой последовательности и работать будет неверно.

Можно использовать сторонюю библиотеку типа commander или yargs.

2023-12-10 08:46 UTC, roovenier commented
> Попробуйте поправить ошибку.
> 
> ```
> ~/projects/dz/node-2023-11/oshchepkov-alex-otus/lesson-1 (nodejs-1 ✗) node ./index.js ./ -d 3
> ./ 3
> ├── README.md
> ├── assets
> node:internal/validators:163
>     throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
>     ^
> 
> TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
> ```

Не совсем понимаю как отловить такую ошибку? С таким вызовом `node ./index.js ./ -d 3` ошибки нет

2023-12-10 16:53 UTC, nlapshin commented on lesson-1/index.js
> +const depthValue = process.argv[4];
Думаю, что в этом дело https://nodejs.org/docs/latest-v18.x/api/fs.html#direntpath path достаточно новая фича.

2023-12-10 16:54 UTC, nlapshin commented on lesson-1/index.js
> +        const files = fs.readdirSync(filePath, { withFileTypes: true });
Тут не критично, но, в целом, используйте асинхронный вызов через promise, он не блокирует event loop

2023-12-16 08:06 UTC, merged